  const Product = [
      /*------------------------------------------Python Courses----------------------------------------------*/
      {
        id: 1,
        title: "Python Fundamentals",
        description: "40 total hours -- 120 lectures",
        price: "22000",
        img: "/Py-images/img1.jpg",
        topic: "Python",
        content: "Master Python fundamentals for a solid foundation and boost in programming.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 2,
        title: "Oops in Python",
        description: "30 total hours -- 60 lectures",
        price: "11500",
        img: "/Py-images/img2.png",
        topic: "Python",
        content: "Unlock the Potential of Python OOP: Revolutionize programming prowess.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 3,
        title: "Python DS & Algo",
        description: "35 total hours -- 50 lectures",
        price: "13000",
        img: "/Py-images/img3.png",
        topic: "Python",
        content: "Python DS & Algo: Unleash the efficiency of data structures and algorithms.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 4,
        title: "Web Development with Python",
        description: "20 total hours -- 20 lectures",
        price: "15000",
        img: "/Py-images/img4.png",
        topic: "Python",
        content: "Python Web Development: Build dynamic, scalable websites with versatility.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 5,
        title: "Data Science & Machine Learning",
        description: "40 total hours -- 116 lectures",
        price: "18000",
        img: "/Py-images/img5.jpg",
        topic: "Python",
        content: "Data Science & ML: Harness the power of data for intelligent insights and boost.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 6,
        title: "GUI Development with Python",
        description: "45 total hours -- 90 lectures",
        price: "18000",
        img: "/Py-images/img6.jpg",
        topic: "Python",
        content: "Unlock the world of GUI development with Python. Create desktop applications.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 7,
        title: "Network Programming in Python",
        description: "24 total hours -- 24 lectures",
        price: "14000",
        img: "/Py-images/img7.jpg",
        topic: "Python",
        content: "Learn Python 3 from scratch! Build 10 network applications using Python.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 8,
        title: "Automation and Scripting",
        description: "60 total hours -- 120 lectures",
        price: "14000",
        img: "/Py-images/img8.jpg",
        topic: "Python",
        content: "Unleash the power of Python for automation & scripting. Streamline workflows.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 9,
        title: "Python for Beginners",
        description: "25 total hours -- 80 lectures",
        price: "9000",
        img: "/Py-images/img9.png",
        topic: "Python",
        content: "Get started with Python programming from scratch. Learn the basics and build a solid foundation.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 10,
        title: "Django Web Development",
        description: "30 total hours -- 50 lectures",
        price: "16000",
        img: "/Py-images/img10.jpeg",
        topic: "Python",
        content: "Build dynamic web applications using Django framework. Master the essentials of web development with Python.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 11,
        title: "Python for Data Analysis",
        description: "35 total hours -- 70 lectures",
        price: "12000",
        img: "/Py-images/img11.jpg",
        topic: "Python",
        content: "Dive into data analysis using Python. Learn how to manipulate, analyze, and visualize data effectively.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 12,
        title: "Python Testing and Debugging",
        description: "20 total hours -- 40 lectures",
        price: "10000",
        img: "/Py-images/img12.jpg",
        topic: "Python",
        content: "Master the art of testing and debugging Python code. Ensure the reliability and quality of your programs.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 13,
        title: "Python for Web Scraping and Automation",
        description: "35 total hours -- 90 lectures",
        price: "16000",
        img: "/Py-images/img13.png",
        topic: "Python",
        content: "Learn how to extract data from websites, automate tasks, and build web scraping applications using Python.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 14,
        title: "Python and Flask for Web Development",
        description: "40 total hours -- 80 lectures",
        price: "18000",
        img: "/Py-images/img14.jpg",
        topic: "Python",
        content: "Develop dynamic web applications using Python and Flask framework. Build and deploy web projects.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 15,
        title: "Python for Ethical Hacking",
        description: "50 total hours -- 100 lectures",
        price: "22000",
        img: "/Py-images/img15.jpg",
        topic: "Python",
        content: "Explore Python's role in ethical hacking. Learn network scanning, vulnerability assessment, and penetration testing.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 16,
        title: "Python for Robotics",
        description: "40 total hours -- 100 lectures",
        price: "20000",
        img: "/Py-images/img16.png",
        topic: "Python",
        content: "Learn how to program robots and control their movements using Python.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 17,
        title: "Python and Big Data Analytics",
        description: "35 total hours -- 80 lectures",
        price: "18000",
        img: "/Py-images/img17.jpg",
        topic: "Python",
        content: "Utilize Python for processing and analyzing large-scale datasets to extract valuable insights.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 18,
        title: "Python for IoT (Internet of Things)",
        description: "30 total hours -- 60 lectures",
        price: "15000",
        img: "/Py-images/img18.jpg",
        topic: "Python",
        content: "Explore how Python is used in building IoT applications and connecting devices to the internet.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 19,
        title: "Python for Computer Vision",
        description: "40 total hours -- 90 lectures",
        price: "19000",
        img: "/Py-images/img19.jpg",
        topic: "Python",
        content: "Dive into computer vision techniques using Python and OpenCV library to analyze and manipulate images and videos.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 20,
        title: "Python and Cloud Computing",
        description: "35 total hours -- 80 lectures",
        price: "17000",
        img: "/Py-images/img20.jpg",
        topic: "Python",
        content: "Learn how to leverage Python for cloud computing tasks, such as managing cloud resources and deploying applications.",
        quantity: 0,
        level: "Advanced"
      },
      /*------------------------------------------Web Development----------------------------------------------*/
      {
        id: 21,
        title: "Basics Web Development",
        description: "28 total hours -- 40 lectures",
        price: "12000",
        topic: "Web Development",
        img: "/WD-images/WD-1.png",
        content: "Unleash creativity with web development: design, code, captivate, shape, innovate.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 22,
        title: "HTML Fundamentals",
        description: "25 total hours -- 50 lectures",
        price: "12500",
        topic: "Web Development",
        img: "/WD-images/WD-2.jpg",
        content: "HTML Basics: Create Engaging Web Pages with Structure, Links, and Accessibility.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 23,
        title: "CSS Styling",
        description: "25 total hours -- 50 lectures",
        price: "13000",
        topic: "Web Development",
        img: "/WD-images/WD-3.jpg",
        content: "Create stunning websites with CSS. Master selection, layouts, colors, and backgrounds.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 24,
        title: "JavaScript Essentials",
        description: "40 total hours -- 120 lectures",
        price: "15000",
        topic: "Web Development",
        img: "/WD-images/WD-4.jpg",
        content: "Master JavaScript essentials: variables, conditionals, functions, DOM manipulation.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 25,
        title: "Front-End Frameworks",
        description: "30 total hours -- 90 lectures",
        price: "18000",
        topic: "Web Development",
        img: "/WD-images/WD-5.png",
        content: "Master front-end frameworks: React, Angular, Vue.js for interactive web experiences.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 26,
        title: "Back-End Development",
        description: "30 total hours -- 90 lectures",
        price: "18000",
        topic: "Web Development",
        img: "/WD-images/WD-6.jpg",
        content: "Master back-end development: languages, data, databases, security for robust web apps.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 27,
        title: "Database and API Integration",
        description: "24 total hours -- 24 lectures",
        price: "25000",
        topic: "Web Development",
        img: "/WD-images/WD-7.jpg",
        content: "Efficiently handle data, APIs, and system integration for seamless web app management.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 28,
        title: "Deployment and Management",
        description: "30 total hours -- 45 lectures",
        price: "14000",
        topic: "Web Development",
        img: "/WD-images/WD-8.png",
        content: "Efficiently deliver projects with control, hosting, optimization, testing, and effective management.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 29,
        title: "Advanced CSS Techniques",
        description: "35 total hours -- 60 lectures",
        price: "15000",
        topic: "Web Development",
        img: "/WD-images/WD-9.jpg",
        content: "Dive deep into advanced CSS techniques and create visually stunning web designs.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 30,
        title: "JavaScript Frameworks",
        description: "40 total hours -- 80 lectures",
        price: "18000",
        topic: "Web Development",
        img: "/WD-images/WD-10.png",
        content: "Master popular JavaScript frameworks like React, Angular, and Vue.js for building interactive web applications.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 31,
        title: "Full-Stack Web Development",
        description: "50 total hours -- 100 lectures",
        price: "22000",
        topic: "Web Development",
        img: "/WD-images/WD-11.jpg",
        content: "Learn both front-end and back-end web development to become a full-stack developer capable of building end-to-end web applications.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 32,
        title: "Responsive Web Design",
        description: "30 total hours -- 60 lectures",
        price: "16000",
        topic: "Web Development",
        img: "/WD-images/WD-12.jpg",
        content: "Learn how to create responsive and mobile-friendly websites that adapt to different screen sizes and devices.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 33,
        title: "Web Accessibility",
        description: "25 total hours -- 40 lectures",
        price: "14000",
        topic: "Web Development",
        img: "/WD-images/WD-13.png",
        content: "Ensure your websites are accessible to all users, including those with disabilities, by implementing web accessibility best practices.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 34,
        title: "Web Performance Optimization",
        description: "35 total hours -- 70 lectures",
        price: "18000",
        topic: "Web Development",
        img: "/WD-images/WD-14.jpg",
        content: "Optimize the performance of your web applications by reducing load times, improving speed, and enhancing user experience.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 35,
        title: "Progressive Web Apps (PWA)",
        description: "40 total hours -- 90 lectures",
        price: "20000",
        topic: "Web Development",
        img: "/WD-images/WD-15.png",
        content: "Learn how to build progressive web apps that offer native app-like experiences across different platforms and devices.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 36,
        title: "Web Security Fundamentals",
        description: "35 total hours -- 60 lectures",
        price: "16000",
        topic: "Web Development",
        img: "/WD-images/WD-16.png",
        content: "Understand the fundamentals of web security and learn how to protect your web applications from common vulnerabilities and attacks.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 37,
        title: "Serverless Web Development",
        description: "30 total hours -- 50 lectures",
        price: "17000",
        topic: "Web Development",
        img: "/WD-images/WD-17.png",
        content: "Build web applications without managing servers using serverless architectures and platforms like AWS Lambda and Firebase.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 38,
        title: "Web Scraping and Automation",
        description: "35 total hours -- 80 lectures",
        price: "18000",
        topic: "Web Development",
        img: "/WD-images/WD-18.png",
        content: "Learn how to extract data from websites and automate tasks using web scraping techniques and tools like Python's BeautifulSoup.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 39,
        title: "GraphQL for Web Development",
        description: "40 total hours -- 90 lectures",
        price: "20000",
        topic: "Web Development",
        img: "/WD-images/WD-19.png",
        content: "Dive into GraphQL and learn how to use this query language for APIs to efficiently fetch and manipulate data in web applications.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 40,
        title: "Web Animation and Effects",
        description: "30 total hours -- 60 lectures",
        price: "16000",
        topic: "Web Development",
        img: "/WD-images/WD-20.png",
        content: "Add life and interactivity to your web applications with animations and effects using CSS, JavaScript, and libraries like GSAP.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 41,
        title: "Microservices Architecture",
        description: "40 total hours -- 90 lectures",
        price: "20000",
        topic: "Web Development",
        img: "/WD-images/WD-21.png",
        content: "Learn how to design and build web applications using a microservices architecture to enhance scalability, modularity, and flexibility.",
        quantity: 0,
        level: "Advanced"
      },
      /*------------------------------------------Data Science----------------------------------------------*/
      {
        id: 42,
        title: "Introduction to Data Science",
        description: "28 total hours -- 40 lectures",
        price: "12000",
        topic: "Data Science",
        img: "/DS/IMG1.png",
        content: "Learn Data Science: Insights, analysis, and informed decision-making online.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 43,
        title: "Data Wrangling and Exploration",
        description: "25 total hours -- 50 lectures",
        price: "12500",
        topic: "Data Science",
        img: "/DS/IMG2.jpg",
        content: "Maximize data potential. Learn wrangling, informed decision-making online.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 44,
        title: "Statistical Analysis",
        description: "25 total hours -- 50 lectures",
        price: "15200",
        topic: "Data Science",
        img: "/DS/IMG3.jpg",
        content: "Unlock statistical analysis power. Master insights, informed decisions online.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 45,
        title: "Machine Learning Fundamentals",
        description: "40 total hours -- 120 lectures",
        price: "20000",
        topic: "Data Science",
        img: "/DS/IMG4.jpg",
        content: "Unleash Machine Learning potential. Master fundamentals, unlock insights.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 46,
        title: "Neural Networks in Data Science",
        description: "30 total hours -- 90 lectures",
        price: "18500",
        topic: "Data Science",
        img: "/DS/IMG5.jpg",
        content: "Deep Learning mastery online. Build intelligent models with techniques.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 47,
        title: "Big Data Analytics",
        description: "30 total hours -- 90 lectures",
        price: "11000",
        topic: "Data Science",
        img: "/DS/IMG6.jpg",
        content: "Unlock Big Data Analytics power. Master techniques, gain insights online.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 48,
        title: "Natural Language Processing",
        description: "24 total hours -- 24 lectures",
        price: "22000",
        topic: "Data Science",
        img: "/DS/IMG7.jpeg",
        content: "Master NLP. Unlock text insights, enhance language understanding online.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 49,
        title: "Data Science Capstone Project",
        description: "30 total hours -- 45 lectures",
        price: "14000",
        topic: "Data Science",
        img: "/DS/IMG8.jpeg",
        content: "Data Science Capstone Project: Solve real-world problems, showcase expertise.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 50,
        title: "Advanced Data Visualization",
        description: "35 total hours -- 20 lectures",
        price: "14500",
        topic: "Data Science",
        img: "/DS/IMG9.jpg",
        content: "Master advanced data visualization techniques online.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 51,
        title: "Time Series Analysis",
        description: "45 total hours -- 30 lectures",
        price: "18000",
        topic: "Data Science",
        img: "/DS/IMG10.jpg",
        content: "Master time series analysis techniques online.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 52,
        title: "Deep Reinforcement Learning",
        description: "60 total hours -- 40 lectures",
        price: "23500",
        topic: "Data Science",
        img: "/DS/IMG11.jpg",
        content: "Master deep reinforcement learning techniques online.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 53,
        title: "Data Ethics and Privacy",
        description: "30 total hours -- 15 lectures",
        price: "10500",
        topic: "Data Science",
        img: "/DS/IMG12.jpg",
        content: "Learn about data ethics and privacy in the context of data science.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 54,
        title: "Cloud Computing for Data Science",
        description: "40 total hours -- 25 lectures",
        price: "16500",
        topic: "Data Science",
        img: "/DS/IMG13.png",
        content: "Master cloud computing techniques for data science projects.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 55,
        title: "Unsupervised Learning Methods",
        description: "55 total hours -- 35 lectures",
        price: "19800",
        topic: "Data Science",
        img: "/DS/IMG14.png",
        content: "Master unsupervised learning techniques online.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 56,
        title: "Data Science for Business",
        description: "50 total hours -- 30 lectures",
        price: "22000",
        topic: "Data Science",
        img: "/DS/IMG15.jpg",
        content: "Understand how data science can benefit businesses and drive strategic decisions.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 57,
        title: "AI for Data Science",
        description: "60 total hours -- 40 lectures",
        price: "25000",
        topic: "Data Science",
        img: "/DS/IMG16.png",
        content: "Explore the intersection of artificial intelligence and data science.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 58,
        title: "Python for Data Science",
        description: "30 total hours -- 20 lectures",
        price: "12000",
        topic: "Data Science",
        img: "/DS/IMG17.jpg",
        content: "Learn how to use Python for data manipulation, analysis, and visualization in data science.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 59,
        title: "R for Data Science",
        description: "35 total hours -- 25 lectures",
        price: "13500",
        topic: "Data Science",
        img: "/DS/IMG18.jpg",
        content: "Learn how to use R for data manipulation, analysis, and visualization in data science.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 60,
        title: "Data Science Interview Prep",
        description: "45 total hours -- 30 lectures",
        price: "18000",
        topic: "Data Science",
        img: "/DS/IMG19.jpg",
        content: "Prepare for data science job interviews with coding exercises, mock interviews, and interview tips.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 61,
        title: "Data Science in Healthcare",
        description: "40 total hours -- 25 lectures",
        price: "16000",
        topic: "Data Science",
        img: "/DS/IMG20.png",
        content: "Explore the applications of data science in the healthcare industry.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 62,
        title: "Reinforcement Learning in Robotics",
        description: "60 total hours -- 40 lectures",
        price: "24000",
        topic: "Data Science",
        img: "/DS/IMG21.jpg",
        content: "Master reinforcement learning for robotics and autonomous systems.",
        quantity: 0,
        level: "Advanced"
      },
    
    
      /*------------------------------------------Java----------------------------------------------*/
      {
        id: 63,
        title: "Introduction to Java",
        description: "28 total hours -- 40 lectures",
        price: "12000",
        img: "/Java/Java1.png",
        topic: "Java",
        content: "Learn the basics of Java programming in this introductory course. Perfect for beginners.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 64,
        title: "Oops in Java",
        description: "25 total hours -- 50 lectures",
        price: "12500",
        img: "/Java/Java2.jpg",
        topic: "Java",
        content: "Learn Java OOP concepts: classes, objects, inheritance, polymorphism, encapsulation, etc.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 65,
        title: "Java Collections Framework",
        description: "25 total hours -- 50 lectures",
        price: "15200",
        img: "/Java/Java3.png",
        topic: "Java",
        content: "The Java Collections Framework helps with collection management, object handling, and manipulation.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 66,
        title: "Java Input/Output and File Handling",
        description: "40 total hours -- 120 lectures",
        price: "20000",
        img: "/Java/Java4.jpg",
        topic: "Java",
        content: "Java I/O & file handling: read/write data, file operations, & stream manipulation.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 67,
        title: "Java Database Connectivity",
        description: "30 total hours -- 90 lectures",
        price: "18500",
        img: "/Java/Java5.png",
        topic: "Java",
        content: "Java DB Connectivity: Connect and interact with databases, server, client using Java.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 68,
        title: "Servlets and JavaServer Pages",
        description: "30 total hours -- 90 lectures",
        price: "11000",
        img: "/Java/Java6.jpg",
        topic: "Java",
        content: "Java web development with server-side programming and dynamic content and routing.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 69,
        title: "JavaServer Faces and Java Persistence API",
        description: "24 total hours -- 24 lectures",
        price: "22000",
        img: "/Java/Java7.jpg",
        topic: "Java",
        content: "JSF: Java's web UI framework | JPA: Java's ORM for efficient database access.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 70,
        title: "Advanced Java Topics",
        description: "30 total hours -- 45 lectures",
        price: "14000",
        img: "/Java/Java8.png",
        topic: "Java",
        content: "Advanced Java: Multithreading, Networking, Databases, Design Patterns, and many more.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 71,
        title: "Java Multithreading",
        description: "20 total hours -- 50 lectures",
        price: "9500",
        img: "/Java/Java9.jpg",
        topic: "Java",
        content: "Learn how to write concurrent programs using Java multithreading techniques.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 72,
        title: "Java Networking",
        description: "18 total hours -- 40 lectures",
        price: "8800",
        img: "/Java/Java10.jpg",
        topic: "Java",
        content: "Explore network programming in Java and learn about sockets, protocols, and communication.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 73,
        title: "Java Design Patterns",
        description: "22 total hours -- 60 lectures",
        price: "10500",
        img: "/Java/Java11.jpg",
        topic: "Java",
        content: "Discover various design patterns and best practices for software development in Java.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 74,
        title: "Java Reflection API",
        description: "12 total hours -- 30 lectures",
        price: "7200",
        img: "/Java/Java12.png",
        topic: "Java",
        content: "Learn how to inspect and manipulate Java classes, interfaces, methods, and fields at runtime.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 75,
        title: "Java GUI Programming",
        description: "24 total hours -- 70 lectures",
        price: "11500",
        img: "/Java/Java13.jpg",
        topic: "Java",
        content: "Build interactive graphical user interfaces (GUIs) using Java's Swing or JavaFX libraries.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 76,
        title: "Java Performance Tuning",
        description: "16 total hours -- 40 lectures",
        price: "8900",
        img: "/Java/Java14.jpeg",
        topic: "Java",
        content: "Learn techniques to optimize and improve the performance of Java applications.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 77,
        title: "Java Security",
        description: "20 total hours -- 50 lectures",
        price: "9800",
        img: "/Java/Java15.png",
        topic: "Java",
        content: "Explore Java's security features and best practices for secure application development.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 78,
        title: "Java Testing and Debugging",
        description: "18 total hours -- 40 lectures",
        price: "8500",
        img: "/Java/Java16.png",
        topic: "Java",
        content: "Learn techniques for testing and debugging Java applications to ensure quality and reliability.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 79,
        title: "Java Web Services",
        description: "22 total hours -- 60 lectures",
        price: "10800",
        img: "/Java/Java17.jpg",
        topic: "Java",
        content: "Learn how to develop and consume SOAP and RESTful web services using Java.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 80,
        title: "Java Microservices",
        description: "24 total hours -- 70 lectures",
        price: "12500",
        img: "/Java/Java18.png",
        topic: "Java",
        content: "Discover the principles and practices of building microservices using Java technologies.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 81,
        title: "Java Serverless Computing",
        description: "16 total hours -- 40 lectures",
        price: "9200",
        img: "/Java/Java19.jpg",
        topic: "Java",
        content: "Explore serverless computing and learn how to develop serverless applications with Java.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 82,
        title: "Java Performance Monitoring",
        description: "18 total hours -- 50 lectures",
        price: "9500",
        img: "/Java/Java20.png",
        topic: "Java",
        content: "Learn how to monitor and analyze the performance of Java applications in real-time.",
        quantity: 0,
        level: "Advanced"
      },
      /*-------------------------------------------------------Cyber Security----------------------------------------------------- */
      {
        id: 83,
        title: "Introduction to Cyber Security",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        topic: "Cyber Security",
        img: "/Cs/img1.png",
        content: "Learn the fundamentals of cyber security and key concepts in protecting digital assets.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 84,
        title: "Network Security",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        topic: "Cyber Security",
        img: "/Cs/img2.png",
        content: "Explore the essential concepts and techniques to secure computer networks.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 85,
        title: "Ethical Hacking",
        description: "50 total hours -- 80 lectures",
        price: "18000",
        topic: "Cyber Security",
        img: "/Cs/img3.jpg",
        content: "Learn the techniques and methodologies of ethical hacking for security assessments.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 86,
        title: "Web Application Security",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        topic: "Cyber Security",
        img: "/Cs/img4.png",
        content: "Discover common vulnerabilities in web applications and methods to mitigate them.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 87,
        title: "Data Privacy and Protection",
        description: "30 total hours -- 40 lectures",
        price: "12500",
        topic: "Cyber Security",
        img: "/Cs/img5.png",
        content: "Learn about privacy laws, data protection mechanisms, and best practices for data privacy.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 88,
        title: "Cryptography",
        description: "35 total hours -- 60 lectures",
        price: "14500",
        topic: "Cyber Security",
        img: "/Cs/img6.jpg",
        content: "Understand the principles of cryptography and encryption algorithms for secure communication.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 89,
        title: "Malware Analysis",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        topic: "Cyber Security",
        img: "/Cs/img7.jpg",
        content: "Learn techniques to analyze and identify malware to protect against cyber threats.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 90,
        title: "Incident Response and Handling",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        topic: "Cyber Security",
        img: "/Cs/img8.jpg",
        content: "Develop skills to respond, investigate, and manage cyber security incidents effectively.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 91,
        title: "Cyber Threat Intelligence",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        topic: "Cyber Security",
        img: "/Cs/img9.jpg",
        content: "Understand the methods to gather, analyze, and apply cyber threat intelligence for proactive defense.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 92,
        title: "Digital Forensics",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        topic: "Cyber Security",
        img: "/Cs/img10.jpg",
        content: "Learn the techniques and tools to investigate digital crimes and gather evidence.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 93,
        title: "Wireless Network Security",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        topic: "Cyber Security",
        img: "/Cs/img11.jpg",
        content: "Explore security measures and vulnerabilities in wireless networks and Wi-Fi.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 94,
        title: "Cloud Security",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        topic: "Cyber Security",
        img: "/Cs/img12.jpg",
        content: "Learn about security challenges and best practices in cloud computing environments.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 95,
        title: "Social Engineering Attacks",
        description: "30 total hours -- 40 lectures",
        price: "13500",
        topic: "Cyber Security",
        img: "/Cs/img13.jpeg",
        content: "Understand the techniques and countermeasures for social engineering attacks.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 96,
        title: "IoT Security",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        topic: "Cyber Security",
        img: "/Cs/img14.jpg",
        content: "Explore security challenges and protocols for securing Internet of Things (IoT) devices.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 97,
        title: "Secure Software Development",
        description: "45 total hours -- 70 lectures",
        price: "17000",
        topic: "Cyber Security",
        img: "/Cs/img15.png",
        content: "Learn secure coding practices and methodologies to develop resilient and secure software.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 98,
        title: "Mobile Application Security",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        topic: "Cyber Security",
        img: "/Cs/img16.jpg",
        content: "Discover vulnerabilities and secure coding practices for mobile application development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 99,
        title: "Penetration Testing",
        description: "50 total hours -- 80 lectures",
        price: "18000",
        topic: "Cyber Security",
        img: "/Cs/img17.jpg",
        content: "Learn how to identify and exploit vulnerabilities in systems through penetration testing.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 100,
        title: "Secure Network Design",
        description: "40 total hours -- 60 lectures",
        price: "15500",
        topic: "Cyber Security",
        img: "/Cs/img18.jpg",
        content: "Develop skills to design and implement secure network architectures and infrastructures.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 101,
        title: "Cybersecurity Governance and Compliance",
        description: "30 total hours -- 40 lectures",
        price: "12500",
        topic: "Cyber Security",
        img: "/Cs/img19.jpg",
        content: "Understand the frameworks and regulations for cybersecurity governance and compliance.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 102,
        title: "Blockchain Security",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        topic: "Cyber Security",
        img: "/Cs/img20.jpg",
        content: "Explore the security aspects and challenges in blockchain technology and cryptocurrencies.",
        quantity: 0,
        level: "Advanced"
      },
      /*------------------------------------------Computer Networks----------------------------------------------*/
      {
        id: 103,
        title: "Introduction to Computer Networks",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        img: "/Cn/img1.jpg",
        topic: "Computer Networks",
        content: "Learn the fundamentals of computer networks and key networking concepts.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 104,
        title: "TCP/IP Protocols",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        img: "/Cn/img2.jpg",
        topic: "Computer Networks",
        content: "Explore the TCP/IP suite of protocols and their role in modern networking.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 105,
        title: "Network Routing and Switching",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        img: "/Cn/img3.jpg",
        topic: "Computer Networks",
        content: "Understand the principles and algorithms behind network routing and switching.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 106,
        title: "Wireless and Mobile Networks",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Cn/img4.jpg",
        topic: "Computer Networks",
        content: "Explore wireless and mobile network technologies, protocols, and security.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 107,
        title: "Network Security",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Cn/img5.jpg",
        topic: "Computer Networks",
        content: "Learn about network security measures, protocols, and best practices.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 108,
        title: "Data Center Networking",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Cn/img6.jpg",
        topic: "Computer Networks",
        content: "Explore the design and management of data center networks for efficient operations.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 109,
        title: "Software-Defined Networking (SDN)",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Cn/img7.jpg",
        topic: "Computer Networks",
        content: "Learn about SDN principles, architectures, and programmability for network management.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 110,
        title: "Network Performance and Optimization",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Cn/img8.jpg",
        topic: "Computer Networks",
        content: "Learn techniques to analyze, optimize, and improve network performance.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 111,
        title: "Network Virtualization",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Cn/img9.jpg",
        topic: "Computer Networks",
        content: "Explore network virtualization concepts and technologies for efficient resource management.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 112,
        title: "Internet of Things (IoT) Networking",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Cn/img10.jpg",
        topic: "Computer Networks",
        content: "Learn about network protocols and architectures for IoT devices and applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 113,
        title: "Network Troubleshooting",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Cn/img11.jpg",
        topic: "Computer Networks",
        content: "Develop skills to diagnose and resolve network issues using troubleshooting techniques.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 114,
        title: "Network Design and Architecture",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Cn/img12.jpg",
        topic: "Computer Networks",
        content: "Learn the principles and best practices for designing and implementing network architectures.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 115,
        title: "Network Management and Administration",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Cn/img13.jpg",
        topic: "Computer Networks",
        content: "Develop skills to manage and administer computer networks efficiently.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 116,
        title: "Network Traffic Analysis",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Cn/img14.jpg",
        topic: "Computer Networks",
        content: "Learn techniques to capture, analyze, and interpret network traffic for performance and security purposes.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 117,
        title: "Network Simulation and Modeling",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Cn/img15.jpg",
        topic: "Computer Networks",
        content: "Explore network simulation tools and techniques to model and evaluate network performance.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 118,
        title: "IPv6 Essentials",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Cn/img16.jpg",
        topic: "Computer Networks",
        content: "Learn the principles and features of IPv6, the next-generation internet protocol.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 119,
        title: "Network Automation",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Cn/img17.jpg",
        topic: "Computer Networks",
        content: "Learn how to automate network tasks and operations using scripting and automation tools.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 120,
        title: "Cloud Networking",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Cn/img18.jpg",
        topic: "Computer Networks",
        content: "Explore networking concepts and technologies for cloud computing environments.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 121,
        title: "VoIP and Unified Communications",
        description: "40 total hours -- 60 lectures",
        price: "15500",
        img: "/Cn/img19.jpg",
        topic: "Computer Networks",
        content: "Learn about Voice over IP (VoIP) and unified communications technologies and protocols.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 122,
        title: "Software-Defined Wide Area Networking (SD-WAN)",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Cn/img20.jpg",
        topic: "Computer Networks",
        content: "Explore SD-WAN concepts and technologies for efficient and secure wide area networking.",
        quantity: 0,
        level: "Intermediate"
      },
      /*-----------------------------------------------------My Sql---------------------------------------------------*/
      {
        id: 123,
        title: "Introduction to MySQL",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        img: "/Mysql/img1.jpg",
        topic: "MySQL",
        content: "Get started with the basics of the MySQL database management system.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 124,
        title: "MySQL Database Design",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        img: "/Mysql/img2.jpg",
        topic: "MySQL",
        content: "Learn the principles and techniques of designing databases with MySQL.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 125,
        title: "MySQL Querying and Data Manipulation",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        img: "/Mysql/img3.jpg",
        topic: "MySQL",
        content: "Master the fundamentals of querying and manipulating data in MySQL.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 126,
        title: "MySQL Stored Procedures and Functions",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Mysql/img4.jpg",
        topic: "MySQL",
        content: "Learn to create stored procedures and functions in MySQL.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 127,
        title: "MySQL Indexing and Optimization",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Mysql/img5.jpg",
        topic: "MySQL",
        content: "Understand indexing techniques and optimize the performance of MySQL databases.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 128,
        title: "MySQL Database Administration",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Mysql/img6.jpg",
        topic: "MySQL",
        content: "Master the skills required for administering and managing MySQL databases.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 129,
        title: "MySQL Security and User Management",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Mysql/img7.jpg",
        topic: "MySQL",
        content: "Learn about security measures and user management in MySQL.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 130,
        title: "MySQL Replication",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Mysql/img8.jpg",
        topic: "MySQL",
        content: "Explore database replication techniques in MySQL for data redundancy and fault tolerance.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 131,
        title: "MySQL Performance Tuning",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Mysql/img9.jpg",
        topic: "MySQL",
        content: "Learn techniques to optimize and improve the performance of MySQL databases.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 132,
        title: "MySQL Backup and Recovery",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Mysql/img10.jpg",
        topic: "MySQL",
        content: "Learn strategies for backup and recovery of MySQL databases in case of failures.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 133,
        title: "MySQL High Availability",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Mysql/img11.jpg",
        topic: "MySQL",
        content: "Explore high availability solutions for MySQL databases.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 134,
        title: "MySQL Data Modeling and ER Diagrams",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Mysql/img12.jpg",
        topic: "MySQL",
        content: "Learn to create entity-relationship (ER) diagrams for data modeling in MySQL.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 135,
        title: "MySQL Triggers and Events",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Mysql/img13.jpg",
        topic: "MySQL",
        content: "Learn to create triggers and events in MySQL for automated actions and scheduling.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 136,
        title: "MySQL Cluster",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Mysql/img14.jpg",
        topic: "MySQL",
        content: "Explore the MySQL Cluster solution for scalable and highly available databases.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 137,
        title: "MySQL Full-Text Search",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Mysql/img15.jpg",
        topic: "MySQL",
        content: "Learn to perform full-text searches in MySQL for efficient text-based searches.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 138,
        title: "MySQL Integration with Programming Languages",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Mysql/img16.jpg",
        topic: "MySQL",
        content: "Explore integrating MySQL with popular programming languages for application development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 139,
        title: "MySQL and PHP",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Mysql/img17.jpg",
        topic: "MySQL",
        content: "Learn to use MySQL with PHP for web application development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 140,
        title: "MySQL and Python",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Mysql/img18.jpg",
        topic: "MySQL",
        content: "Explore using MySQL with Python for data manipulation and analysis.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 141,
        title: "MySQL and Node.js",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Mysql/img19.jpg",
        topic: "MySQL",
        content: "Learn to use MySQL with Node.js for server-side web development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 142,
        title: "MySQL Performance Optimization",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Mysql/img20.jpg",
        topic: "MySQL",
        content: "Master advanced techniques for optimizing the performance of MySQL databases.",
        quantity: 0,
        level: "Advanced"
      },
      /*------------------------------------------React----------------------------------------------*/
      {
        id: 143,
        title: "Introduction to React",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        img: "/React/img1.png",
        topic: "React",
        content: "Get started with the basics of React library for building user interfaces.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 144,
        title: "React Serverless Functions (AWS Lambda)",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/React/img2.png",
        topic: "React",
        content: "Explore integrating React with serverless functions using AWS Lambda.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 145,
        title: "React Progressive Web Apps (PWA)",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/React/img3.png",
        topic: "React",
        content: "Learn to build progressive web apps (PWAs) using React.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 146,
        title: "React Deployment and Continuous Integration",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img4.png",
        topic: "React",
        content: "Learn to deploy and automate the deployment process for React applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 147,
        title: "React Design Patterns",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/React/img5.png",
        topic: "React",
        content: "Explore common design patterns and best practices in React development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 148,
        title: "React Animation and Transitions",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img6.png",
        topic: "React",
        content: "Learn to add animations and transitions to React components and UI.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 149,
        title: "React Components",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        img: "/React/img7.png",
        topic: "React",
        content: "Learn to build reusable components in React for modular UI development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 150,
        title: "React State Management",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        img: "/React/img8.png",
        topic: "React",
        content: "Master state management techniques in React for maintaining application state.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 151,
        title: "React Hooks",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/React/img9.png",
        topic: "React",
        content: "Explore React hooks for managing state and side effects in functional components.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 152,
        title: "React Routing",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/React/img10.png",
        topic: "React",
        content: "Learn to implement client-side routing in React for building single-page applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 153,
        title: "React Forms and Validation",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/React/img11.png",
        topic: "React",
        content: "Learn to handle forms and perform input validation in React applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 154,
        title: "React Context API",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img12.png",
        topic: "React",
        content: "Explore React's Context API for managing global state in component trees.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 155,
        title: "React and Redux",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/React/img13.png",
        topic: "React",
        content: "Learn to integrate Redux with React for predictable state management.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 156,
        title: "React and GraphQL",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/React/img14.png",
        topic: "React",
        content: "Explore integrating React with GraphQL for efficient data fetching.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 157,
        title: "React and Firebase",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img15.png",
        topic: "React",
        content: "Learn to build real-time applications with React and Firebase backend.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 158,
        title: "React Testing",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/React/img16.png",
        topic: "React",
        content: "Develop skills in testing React components and applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 159,
        title: "React Performance Optimization",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/React/img17.png",
        topic: "React",
        content: "Learn techniques to optimize and improve the performance of React applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 160,
        title: "Server-Side Rendering (SSR) with React",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img18.png",
        topic: "React",
        content: "Learn to render React components on the server for improved performance and SEO.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 161,
        title: "React Native Mobile App Development",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/React/img19.png",
        topic: "React",
        content: "Build mobile applications using React Native for iOS and Android platforms.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 162,
        title: "React and TypeScript",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/React/img20.png",
        topic: "React",
        content: "Explore using TypeScript with React for static typing and enhanced tooling.",
        quantity: 0,
        level: "Intermediate"
      },
      /*------------------------------------------------------------Vue Js------------------------------------------------------- */
      {
        id: 163,
        title: "Introduction to Vue.js",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        img: "/Vue/img1.png",
        topic: "Vue.js",
        content: "Get started with the basics of Vue.js library for building user interfaces.",
        quantity: 0,
        level: "Beginner"
      },
        {
        id: 164,
        title: "Vue Deployment and Continuous Integration",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Vue/img2.png",
        topic: "VueJs",
        content: "Learn to deploy and automate the deployment process for Vue.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 165,
        title: "Vue Design Patterns",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Vue/img3.png",
        topic: "VueJs",
        content: "Explore common design patterns and best practices in Vue.js development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 166,
        title: "Vue Advanced Topics",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Vue/img4.png",
        topic: "VueJs",
        content: "Explore advanced topics and features in Vue.js.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 167,
        title: "Vue Native Mobile App Development",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Vue/img5.png",
        topic: "VueJs",
        content: "Learn to develop native mobile applications using Vue Native.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 168,
        title: "Vue and Electron",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Vue/img6.png",
        topic: "VueJs",
        content: "Explore building desktop applications using Vue.js and Electron framework.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 169,
        title: "Vue Components",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        img: "/Vue/img7.png",
        topic: "VueJs",
        content: "Learn to build reusable components in Vue.js for modular UI development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 170,
        title: "Vue State Management (Vuex)",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        img: "/Vue/img8.png",
        topic: "VueJs",
        content: "Master state management techniques using Vuex in Vue.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 171,
        title: "Vue Routing",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Vue/img9.png",
        topic: "VueJs",
        content: "Learn to implement client-side routing in Vue.js for building single-page applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 172,
        title: "Vue Forms and Validation",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Vue/img10.png",
        topic: "VueJs",
        content: "Learn to handle forms and perform input validation in Vue.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 173,
        title: "Vue and RESTful APIs",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Vue/img11.png",
        topic: "VueJs",
        content: "Explore integrating Vue.js with RESTful APIs for data retrieval and manipulation.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 174,
        title: "Vue Authentication and Authorization",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Vue/img12.png",
        topic: "VueJs",
        content: "Learn to implement authentication and authorization in Vue.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 175,
        title: "Vue Testing",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Vue/img13.png",
        topic: "VueJs",
        content: "Develop skills in testing Vue.js components and applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 176,
        title: "Vue Animation and Transitions",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Vue/img14.png",
        topic: "VueJs",
        content: "Learn to add animations and transitions to Vue.js components and UI.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 177,
        title: "Vue and TypeScript",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Vue/img15.png",
        topic: "VueJs",
        content: "Explore using TypeScript with Vue.js for type safety and enhanced development.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 178,
        title: "Vue Server-Side Rendering (SSR)",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Vue/img16.png",
        topic: "VueJs",
        content: "Learn to render Vue.js components on the server for improved performance and SEO.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 179,
        title: "Vue and Firebase",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Vue/img17.png",
        topic: "VueJs",
        content: "Learn to build real-time applications with Vue.js and Firebase backend.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 180,
        title: "Vue and GraphQL",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Vue/img18.png",
        topic: "VueJs",
        content: "Explore integrating Vue.js with GraphQL for efficient data fetching.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 181,
        title: "Vue UI Libraries and Component Styling",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Vue/img19.png",
        topic: "VueJs",
        content: "Explore popular UI libraries and styling approaches for Vue.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 182,
        title: "Vue Progressive Web Apps (PWA)",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Vue/img20.png",
        topic: "VueJs",
        content: "Learn to build progressive web apps (PWAs) using Vue.js.",
        quantity: 0,
        level: "Intermediate"
      },
      /*------------------------------------------------------------Nextjs------------------------------------------------------- */
      {
        id: 183,
        title: "Introduction to Next.js",
        description: "30 total hours -- 40 lectures",
        price: "12000",
        img: "/Next/img1.png",
        topic: "Next.js",
        content: "Get started with the basics of Next.js for building server-rendered React applications.",
        quantity: 0,
        level: "Beginner"
      },
      {
        id: 184,
        title: "Next.js API Routes",
        description: "35 total hours -- 50 lectures",
        price: "13500",
        img: "/Next/img2.png",
        topic: "Next.js",
        content: "Explore building API routes and serverless functions in Next.js.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 185,
        title: "Next.js Data Fetching",
        description: "40 total hours -- 60 lectures",
        price: "16000",
        img: "/Next/img3.png",
        topic: "Next.js",
        content: "Learn various data fetching techniques in Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 186,
        title: "Next.js Deployment",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Next/img4.png",
        topic: "Next.js",
        content: "Learn to deploy Next.js applications to various hosting platforms.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 187,
        title: "Next.js Advanced Topics",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Next/img5.png",
        topic: "Next.js",
        content: "Explore advanced topics and features in Next.js.",
        quantity: 0,
        level: "Advanced"
      },
      {
        id: 188,
        title: "Next.js Authentication",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Next/img6.png",
        topic: "Next.js",
        content: "Implement authentication and user management in Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 189,
        title: "Next.js E-commerce",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Next/img7.png",
        topic: "Next.js",
        content: "Build an e-commerce platform with Next.js and popular frameworks.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 190,
        title: "Next.js Internationalization (i18n)",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Next/img8.png",
        topic: "Next.js",
        content: "Implement internationalization (i18n) in Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 191,
        title: "Next.js Optimizations",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Next/img9.png",
        topic: "Next.js",
        content: "Optimize Next.js applications for performance and better user experience.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 192,
        title: "Next.js Routing and Navigation",
        description: "40 total hours -- 60 lectures",
        price: "15000",
        img: "/Next/img10.png",
        topic: "Next.js",
        content: "Learn to implement routing and navigation in Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 193,
        title: "Next.js Server-Side Rendering (SSR)",
        description: "35 total hours -- 50 lectures",
        price: "14500",
        img: "/Next/img11.png",
        topic: "Next.js",
        content: "Master server-side rendering in Next.js for improved performance and SEO.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 194,
        title: "Next.js Static Site Generation (SSG)",
        description: "45 total hours -- 70 lectures",
        price: "17500",
        img: "/Next/img12.png",
        topic: "Next.js",
        content: "Learn to generate static websites with Next.js for high performance and scalability.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 195,
        title: "Next.js Styling",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Next/img13.png",
        topic: "Next.js",
        content: "Learn various styling techniques and frameworks for Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 196,
        title: "Next.js Testing",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Next/img14.png",
        topic: "Next.js",
        content: "Develop skills in testing Next.js components and applications.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 197,
        title: "Next.js and GraphQL",
        description: "40 total hours -- 60 lectures",
        price: "16500",
        img: "/Next/img15.png",
        topic: "Next.js",
        content: "Explore integrating Next.js with GraphQL for efficient data fetching.",
        quantity: 0,
        level: "Intermediate"
      },
      {
        id: 198,
        title: "Next.js and Prisma",
        description: "35 total hours -- 50 lectures",
        price: "14000",
        img: "/Next/img16.png",
        topic: "Next.js",
        content: "Learn to use Prisma as the data layer in Next.js applications.",
        quantity: 0,
        level: "Intermediate"
      },
    ];
    
    export default Product;
    